SET IDENTITY_INSERT [dbo].[Attributes] ON
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (1, N'Ürün Boyutu:', 9, N'200gr')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (2, N'Ürün Adı:', 4, N'Signal White Now')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (3, N'Ürün Markası:', 9, N'MİLUPA')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (4, N'Ürün Adı:', 9, N'Milupa Papatya Çayı')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (5, N'Ürün Faydaları:', 10, N'Sindirim sistemini düzenler, hazımsızlığı giderir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (6, N'Ürün Faydaları:', 10, N'Cilt tonu eşitsizliği, koyu lekeler, çizgi ve kırışıklık görünümü, sıkılık kaybına karşı bakım sağlayan tek bir akıllı serum.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (7, N'Özet Bilgi:', 10, N'Tüm cilt tiplerine uygundur.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (8, N'Ürün Boyutu:', 10, N'30ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (9, N'Ürün Markası:', 10, N'CLINIQUE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (10, N'Ürün Adı:', 10, N'Clinique Smart Custom Repair Serum')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (11, N'Özet Bilgi:', 9, N'Kaynamakta olan 100ml suya tepeleme 1 tatlı kaşığı 5g milupa papatya çayı ilave ederek karıştırınız.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (12, N'Ürün Faydaları:', 11, N'Aktif arındırıcılar içeren Atoderm Intensive Foaming Gel cilt kuruluğunun ilerlemesine karşı bakım sağlar.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (13, N'Ürün Boyutu:', 11, N'200ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (14, N'Ürün Markası:', 11, N'BIODERMA')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (15, N'Ürün Adı:', 11, N'Bioderma Atoderm Gel')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (16, N'Ürün Faydaları:', 12, N'Cildi temizlemeye, kir ve makyajdan arındırmaya yardımcı olur.Sebum salgısını kontrol altına alarak aşırı yağlanmanın önüne geçmeyi hedefler.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (17, N'Özet Bilgi:', 12, N'Karma ve yağlı ciltler için sabun içermeyen temizleme jeli')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (18, N'Ürün Boyutu:', 12, N'500ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (19, N'Ürün Markası:', 12, N'BIODERMA')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (20, N'Ürün Adı:', 12, N'Bioderma Sebium Foaming')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (21, N'Ürün Faydaları:', 13, N'Günlük oluşan olumsuz etkenlerin giderilmesinde yardımcı olur')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (22, N'Özet Bilgi:', 11, N'Çok kuru ve atopik ciltler için ultra zengin yatıştırıcı ve temizleyici jel.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (23, N'Özet Bilgi:', 13, N'%89 Vichy Termal Suyu ve doğal hyalüronik asit içeren serum,Parfüm ve boya içermez.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (24, N'Ürün Adı:', 8, N'Betamega Takviye Edici Şurup')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (25, N'Ürün Boyutu:', 8, N'200gr')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (26, N'Ürün Boyutu:', 5, N'75ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (27, N'Ürün Markası:', 5, N'PARADONTAX')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (28, N'Ürün Adı:', 5, N'Parodontax Beyazlatıcı Diş Macunu')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (29, N'Ürün Faydaları:', 6, N'Uykuda,yüzerken,sörfte,duşta,seyahat ederken,çalışırken ve dinlenme anlarında gürültüyü engellemeye yardımcı olur.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (30, N'Özet Bilgi:', 6, N'Yüksek hararetli ortamlarda tavsiye edilmez.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (31, N'Ürün Boyutu:', 6, N'4 adet')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (32, N'Ürün Markası:', 6, N'MOOS')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (33, N'Ürün Adı:', 6, N'Moos Kulak Tıkacı')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (34, N'Ürün Faydaları:', 7, N'%90''a kadar doğru sonuç verir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (35, N'Ürün Markası:', 8, N'MİLUPA')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (36, N'Özet Bilgi:', 7, N'%100 su geçirmez.Ölçüm başlama/bitiş uyarısı.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (37, N'Ürün Markası:', 7, N'VIVOCARE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (38, N'Ürün Adı:', 7, N'Vivocare Ateş Ölçer')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (39, N'Ürün Faydaları:', 18, N'Sıvıyı hapseder, kuruluk hissi verir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (40, N'Özet Bilgi:', 18, N'Large boy yetişkin bezi.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (41, N'Ürün Boyutu:', 18, N'30 Adet')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (42, N'Ürün Markası:', 18, N'TENA')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (43, N'Ürün Adı:', 18, N'Tena Slip Plus')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (44, N'Ürün Faydaları:', 8, N'Sindirim sistemini düzenler, hazımsızlığı giderir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (45, N'Özet Bilgi:', 8, N'Kaynamakta olan 100ml suya tepeleme 1 tatlı kaşığı 5g milupa papatya çayı ilave ederek karıştırınız.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (46, N'Ürün Boyutu:', 7, N'10cm')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (47, N'Özet Bilgi:', 5, N'Diş eti kanaması, sağlıksız diş etinin ilk belirtilerinden biridir. Önlem alınmazsa, diş kaybına sebep olabilir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (48, N'Ürün Boyutu:', 13, N'50ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (49, N'Ürün Adı:', 13, N'Vichy Mineral 89% Mineralizing Water + Hyaluronic Acid')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (50, N'Ürün Adı:', 2, N'Avene 50+ Güneş Koruyucu')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (51, N'Ürün Markası:', 2, N'AVENE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (52, N'Ürün Boyutu:', 2, N'50ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (53, N'Ürün Faydaları:', 17, N'Kepekle mücadele eder, saçınıza bakım yapar.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (54, N'Özet Bilgi:', 17, N'Islak saça masaj yaparak köpürtün, durulayın.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (55, N'Ürün Boyutu:', 17, N'200ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (56, N'Ürün Markası:', 17, N'PANTENE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (57, N'Ürün Adı:', 17, N'Pantene Kepeğe Karşı Etkili Şampuan')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (58, N'Özet Bilgi:', 2, N'Etkili bir güneş koruması sağlayan renkli krem.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (59, N'Ürün Faydaları:', 3, N'Diş ve diş etini plaklara ve çürüklere karşı koruyor, diş taşı oluşumunu geciktiriyor. ')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (60, N'Ürün Faydaları:', 2, N'Yüksek koruma faktörü ile renkli güneş koruyucu bakım ürünüdür.Renkli yapısı ile cilt kusurlarını kapamada yardımcı olur')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (61, N'Ürün Markası:', 1, N'SEBAMED')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (62, N'Ürün Faydaları:', 19, N'Zayıf saçlarda güç ve görünür parlaklık için Sinameki ile zenginleştirilmiştir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (63, N'Özet Bilgi:', 19, N'Islak saça masaj yaparak köpürtün, durulayın.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (64, N'Ürün Boyutu:', 19, N'100ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (65, N'Ürün Markası:', 19, N'PANTENE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (66, N'Ürün Adı:', 19, N'Pantene Güç ve Parlaklık Bakım Şampuanı')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (67, N'Ürün Boyutu:', 1, N'150ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (68, N'Özet Bilgi:', 1, N'Yağ, alkol ve renklendirici madde içermez.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (69, N'Ürün Faydaları:', 1, N'Yüksek etkili 98 UVA ve 30, 45, 50 UVB filtreleri sayesinde güneşin zararlı ışınlarını süzer.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (70, N'Ürün Adı:', 1, N'Sebamed 45+ Güneş Koruyucu')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (71, N'Ürün Markası:', 13, N'VICHY')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (72, N'Ürün Adı:', 16, N'Pantene Aqualight Şampuan')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (73, N'Ürün Boyutu:', 16, N'200ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (74, N'Ürün Faydaları:', 14, N'Saçların günlük hijyeni,bakımı ve korunması içindir. Babe Ekstra Yumuşak Şampuan saçların ihtiyaç duyduğu temizliği ve bakımı sağlama konusunda yardımcı bir üründür.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (75, N'Özet Bilgi:', 14, N'Islak saça masaj yaparak köpürtün, durulayın.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (76, N'Ürün Boyutu:', 14, N'200ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (77, N'Ürün Markası:', 14, N'BABE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (78, N'Ürün Adı:', 14, N'Babe Extra Mild Şampuan')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (79, N'Ürün Markası:', 4, N'SIGNAL')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (80, N'Ürün Boyutu:', 4, N'75ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (81, N'Özet Bilgi:', 4, N'Sigara kaynaklı leke görünümlerini azaltmaya yardımcı olur.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (82, N'Ürün Faydaları:', 4, N'Özel geliştirilen yeni White Now Man içeriğindeki mavi ışık partikülleri sayesinde beyazlık sağlar ve sigara kaynaklı lekeleri giderir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (83, N'Ürün Markası:', 16, N'PANTENE')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (84, N'Ürün Faydaları:', 15, N'Bit ve yumurtalarını öldürür, kaşıntıyı giderir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (85, N'Ürün Boyutu:', 15, N'100ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (86, N'Ürün Markası:', 15, N'BAYBIT')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (87, N'Ürün Adı:', 15, N'Bit Temizleyici Şampuan')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (88, N'Ürün Adı:', 3, N'La Roche Posay 50+ Güneş Koruyucu')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (89, N'Ürün Markası:', 3, N'La Roche Posay')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (90, N'Ürün Boyutu:', 3, N'50ml')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (91, N'Özet Bilgi:', 3, N'Diş eti kanaması, sağlıksız diş etinin ilk belirtilerinden biridir. Önlem alınmazsa, diş kaybına sebep olabilir.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (92, N'Ürün Faydaları:', 16, N'Mikro-güçlendiriciler içeren bu formül, ince telli saçları hedefleyerek ağırlaştırmadan güçlendirmeye* yardımcı olur.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (93, N'Özet Bilgi:', 16, N'Islak saça masaj yaparak köpürtün, durulayın.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (94, N'Özet Bilgi:', 15, N'Islak saça masaj yaparak köpürtün, 1 saat bekledikten sonra durulayın.')
INSERT INTO [dbo].[Attributes] ([ProductAttributeId], [Attribute], [ProductId], [Value]) VALUES (95, N'Ürün Faydaları:', 5, N'Diş ve diş etini plaklara ve çürüklere karşı koruyor, diş taşı oluşumunu geciktiriyor. ')
SET IDENTITY_INSERT [dbo].[Attributes] OFF
